baseURL = 'https://bloomadoo.com/'
title = 'Bloomadoo first test site'
theme = 'hugo-universal-theme-master'
style = "blue"
languageCode = 'en-us'
defaultContentLanguage = "en"

[menu]


# Main menu

[[menu.main]]
    name       = "Contact"
    identifier = "Contact"
    url        = "/"
    weight     = 2

[[menu.main]]
    name       = "Home"
    identifier = "Main Menu"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Option 1: Starting page"
    url        = "/"
    weight     = 1
    parent     = "Main Menu"

[[menu.main]]
    name       = "Option 2: Who are we?"
    url        = "/"
    weight     = 2
    parent     = "Main Menu"

[[menu.main]]
    name       = "Option 3: Existential crisis"
    url        = "/"
    weight     = 3
    parent     = "Main Menu"

[params.topbar]
    enable = true
    text = "<p>Contact us on +123 456 789 or whatever@bloomadoo.com</p>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fas fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/attila.rakos.5/"
    pre = "<i class='fas fa-2x fa-facebook'></i>"


[params]
    viewMorePostLink = "/blog/"
    mainSections = ["blog"]
    defaultDescription = "Site template made by Attila using Hugo"

    disabled_logo = false
    logo_text = "Bloomadoo"
    defaultKeywords = ["Bloomadoo", "training", "continuous improvement"]
    dropdown_mouse_over = false
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

[params.widgets]
    search = true
    categories = true
    tags = true

[params.see_more]
     # The background image is: \themes\hugo-universal-theme-master\static\img\fixed-background-2.jpg
    enable = true
    icon = "far fa-file-alt"
    title = "Get the light that is needed for your growing?"
    subtitle = "We have prepared for you everything."
    link_url = "#"
    link_text = "Best info comes from here"

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Whatever blabla fits here goes well with the blog posts."
    hide_summary = false

[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.clients]
    enable = true
    title = "Our Partners"
    subtitle = "We have proudly collaborated with the following major worldwide companies."


[params.carouselTestimonials]
     # All carousel items are defined in their own files in the data folder.
     # The background image is based in themes/hugo-universal../static/img/photogrid.jpg
    enable = true
    auto_play = false
    items = 2
    slide_speed = 2000
    pagination_speed = 1000